import 'package:flutter/material.dart';
import 'package:equatable/equatable.dart';

/// generate by https://javiercbk.github.io/json_to_dart/
class AutogeneratedHome {
  List<HomeModel> results;

  AutogeneratedHome({this.results});

  AutogeneratedHome.fromJson(Map<String, dynamic> json) {
    if (json['results'] != null) {
      results = List<HomeModel>();
      json['results'].forEach((v) {
        results.add(HomeModel.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (this.results != null) {
      data['results'] = this.results.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class HomeModel extends Equatable {
  final int id;
  final String name;

  HomeModel({this.id, this.name});

  @override
  List<Object> get props => [id, name];

  static HomeModel fromJson(Map<String, dynamic> json) {    
    return HomeModel(id: json['id'], name: json['name']);
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['name'] = this.name;
    return data;
  }
}

class UserStatDto {
  int totalCount;
  String statTitle;
  String statDescription;
  IconData icon;

  UserStatDto({this.totalCount, this.statTitle, this.statDescription, this.icon});
}

class UserStatisticsDashboardDto {
  int totalAssignedCustomer;
  int totalNewCustomerInAMonth;
  int totalCustomerWithOrderInAMonth;
  int totalPercentCustomerVisitInAMonth;
  int salesTargetInAMonth;
  int customerMTDInAMonth;
  int percentSalesTargetInAMonth;
  int totalCustomerVisitFeedbackInAMonth;
  int percentCustomerWithOrderInAMonth;
  int percentNewCustomerInAMonth;
  int customerMTGInAMonth;
  int percentMTGInAMonth;

  UserStatisticsDashboardDto(
      {this.totalAssignedCustomer,
      this.totalNewCustomerInAMonth,
      this.totalCustomerWithOrderInAMonth,
      this.totalPercentCustomerVisitInAMonth,
      this.salesTargetInAMonth,
      this.customerMTDInAMonth,
      this.percentSalesTargetInAMonth,
      this.totalCustomerVisitFeedbackInAMonth,
      this.percentCustomerWithOrderInAMonth,
      this.percentNewCustomerInAMonth,
      this.customerMTGInAMonth,
      this.percentMTGInAMonth});

  UserStatisticsDashboardDto.fromJson(Map<String, dynamic> json) {
    totalAssignedCustomer = json['TotalAssignedCustomer'];
    totalNewCustomerInAMonth = json['TotalNewCustomerInAMonth'];
    totalCustomerWithOrderInAMonth = json['TotalCustomerWithOrderInAMonth'];
    totalPercentCustomerVisitInAMonth =
        json['TotalPercentCustomerVisitInAMonth'];
    salesTargetInAMonth = json['SalesTargetInAMonth'];
    customerMTDInAMonth = json['CustomerMTDInAMonth'];
    percentSalesTargetInAMonth = json['PercentSalesTargetInAMonth'];
    totalCustomerVisitFeedbackInAMonth =
        json['TotalCustomerVisitFeedbackInAMonth'];
    percentCustomerWithOrderInAMonth = json['PercentCustomerWithOrderInAMonth'];
    percentNewCustomerInAMonth = json['PercentNewCustomerInAMonth'];
    customerMTGInAMonth = json['CustomerMTGInAMonth'];
    percentMTGInAMonth = json['PercentMTGInAMonth'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['TotalAssignedCustomer'] = this.totalAssignedCustomer;
    data['TotalNewCustomerInAMonth'] = this.totalNewCustomerInAMonth;
    data['TotalCustomerWithOrderInAMonth'] =
        this.totalCustomerWithOrderInAMonth;
    data['TotalPercentCustomerVisitInAMonth'] =
        this.totalPercentCustomerVisitInAMonth;
    data['SalesTargetInAMonth'] = this.salesTargetInAMonth;
    data['CustomerMTDInAMonth'] = this.customerMTDInAMonth;
    data['PercentSalesTargetInAMonth'] = this.percentSalesTargetInAMonth;
    data['TotalCustomerVisitFeedbackInAMonth'] =
        this.totalCustomerVisitFeedbackInAMonth;
    data['PercentCustomerWithOrderInAMonth'] =
        this.percentCustomerWithOrderInAMonth;
    data['PercentNewCustomerInAMonth'] = this.percentNewCustomerInAMonth;
    data['CustomerMTGInAMonth'] = this.customerMTGInAMonth;
    data['PercentMTGInAMonth'] = this.percentMTGInAMonth;
    return data;
  }
}
