const String kFirebaseAuthToken = "firebase-auth-token";
const String kBaseUrl = "http://167.71.198.108:8080/";
// const String kBaseUrl = "http://127.0.0.1:8080/";
const String kFirebaseStorageBucket = 'gs://hali-ca190.appspot.com';
const String kAppVersion = '0.0.1';
const String kApiKey = "AIzaSyBVqdI_6VYHN_kjmftunkxUHSlAdtWNYX4";
const String kFirebaseUser = "firebase-user-app";
const String kDefaultUserPhotoUrl = "https://firebasestorage.googleapis.com/v0/b/hali-ca190.appspot.com/o/public_images%2Fic-avatar.png?alt=media&token=dce7d106-701c-4a9b-8c38-a29ce0509582";
// const String kDbProvider = "firestore";
const String kDbProvider = "mysql";